nav:
- Di치rio oficial - 07/02/2025: 2025-02-07.md
- Di치rio oficial - 10/02/2025: 2025-02-10.md
- Di치rio oficial - 11/02/2025: 2025-02-11.md
site_name: Resumo di치rio oficial de Porto Alegre
theme:
  name: material
  palette:
    primary: red
