name: Build Site from MkDocs

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
    paths:
      - 'docs/**'  # Trigger only if changes are made inside /docs
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow push access
      pages: write      # Allow GitHub Pages deployment
      id-token: write   # Required for secure authentication

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use default token

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
